language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t chrisstjax/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chrisstjax/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-673092279265"
  bucket_path: "docker-react"
  on:
    branch: master